volumes:
  db_vol:
  wp_vol:

networks:
  wp_net:
    driver: bridge

services:
  wordpress:
    image: wordpress  
    container_name: wp
    ports:
      - "80:80"  
    environment:
      WORDPRESS_DB_HOST: db 
      WORDPRESS_DB_USER: wordpress  
      WORDPRESS_DB_PASSWORD: wordpress  
      WORDPRESS_DB_NAME: wordpress  
    volumes:
      - wp_vol:/var/www/html
    networks:
      - wp_net
    restart: unless-stopped  
    depends_on:
      - db
  db:
    image: mysql
    container_name: mysql-2
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: wordpress  
      MYSQL_PASSWORD: wordpress  
      MYSQL_DATABASE: wordpress  
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - wp_net
    restart: unless-stopped
      
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 81:8080
    networks:
      - wp_net

